Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed
        Type: String

    VpcCIDR:
        Description: No description
        Type: String
        Default: 10.0.0.0/16

Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: !Ref VpcCIDR
            EnableDnsHostnames: true
            Tags:
              - Key: Name
                Value: !Ref EnvironmentName
    InternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
              - Key: Name
                Value: !Ref EnvironmentName
    InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGateWayId: !Ref InternetGateway
            VpcId: !Ref VPC
